# Generated by Django 3.2.3 on 2021-05-25 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_ids', models.CharField(max_length=200)),
                ('movie_id', models.IntegerField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=100, null=True)),
                ('original_title', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.CharField(blank=True, max_length=5000, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=5000, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('video', models.BooleanField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_rank', to='movies.movie')),
            ],
        ),
    ]
